version: "3.7"
services:
  node:
    build:
      context: .
    environment:
      NUXT_PUBLIC_BACKEND_URL: "https://api.romain-quentel.ovh/"
    ports:
      - "4000:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.site_perso.rule=Host(`romain-quentel.ovh`)"
      - "traefik.http.routers.site_perso.entrypoints=websecure"
      - "traefik.http.routers.site_perso.tls=true"
      - "traefik.http.routers.site_perso.tls.certresolver=defaultResolver"
